### ISSUE TITLE
Singular and multiple remove media checkboxes have reversed checked semantics

### ISSUE THREAD

**Issue by botandrose** [botandrose/ds_media_library#6]
So in the singular case, the checkbox is something like:
```
<input type="checkbox" name="widget[remove_cat_picture]" value="1" checked="checked"/>
```
When checked, this tells the server to remove the cat picture.

However, in the multiple case, the checkboxes are a list of ids of selected media, like:
```
<input type="checkbox" value="1" checked="checked" name="widget[dog_picture_ids][]">
<input type="checkbox" value="2" checked="checked" name="widget[dog_picture_ids][]">
<input type="checkbox" value="3" checked="checked" name="widget[dog_picture_ids][]">
```
When submitted, the checked boxes are the list of selected media. If one is unchecked, the server does not receive it.

This means that in the singular state, checked means remove, but in the multiple state, checked means keep. :(

Unfortunately, due to the way html forms work, this is honestly the best solution I can come up with, so you'll have to paper around this with CSS. Sorry.

**Comment by botandrose** [comment]
@gubito Actually I got an idea. Lemme try to make them both reversed, but at least they'd be consistent with each other. On me.

**Comment by botandrose** [comment]
@gubito Success! Okay, just on you now to invert the checkbox displays.

**Comment by gubito** [comment]
@botandrose Fixed and pushed
